export const PortfolioConsts = [
  {
    image: "todo-image.png",
    title: "Todo App",
    tech: ["HTML", "CSS", "JavaScript"],
    features: [
      "Add and delete todos",
      "Swap position of todos",
      "Pagination for better navigation",
      "Data persistence using local storage",
    ],
    live: "https://todo-list-app-eight-ashy.vercel.app/",
  },
  {
    image: "mini-ecom_compressed.png",
    title: "Mini E-Commerce",
    tech: ["HTML", "CSS", "JavaScript"],
    features: [
      "Add products to cart with real-time updates",
      "Cart persists using local storage",
      "Stock tracking and dynamic stock updates",
      "Disables 'Add to Cart' based on stock availability",
      "Cart displays total sum and allows item removal",
      "Pagination on product listing page",
    ],
    live: "https://mini-e-commerce-xi.vercel.app/",
  },
  {
    image: "movie-finder_compressed.png",
    title: "Movie Finder",
    tech: ["React JS"],
    features: [
      "Browse most popular movies with pagination",
      "Search functionality with debounce optimization",
      "Mark movies as favorites and toggle saved list",
      "Favorites stored in local storage",
      "Detailed movie view on click",
    ],
    live: "https://movie-finder-seven-chi.vercel.app/",
  },
  {
    image: "blog-image_compressed.png",
    title: "Blog App",
    tech: [
      "AI",
      "MongoDB",
      "Express JS",
      "Node JS",
      "React JS",
      "Tailwind CSS",
    ],
    features: [
      "Admin can create, draft, publish, or auto-generate posts using AI",
      "Set categories and upload featured images via ImageKit",
      "Search and filter posts by status in admin panel",
      "Comment moderation: approve or delete",
      "JWT-based persistent login and protected routes",
      "Users can browse, search, and filter posts",
      "Authenticated users can comment (pending approval)",
      "Users can delete their own comments",
      "Admin can bulk-delete comments per post",
      "Pagination for posts and comments for clean UX",
    ],
    live: "https://blog-app-mern-frontend-uv33.onrender.com/",
  },
  {
    image: "portfolio-image.png",
    title: "Portfolio Site",
    tech: ["TypeScript", "Next JS", "Tailwind CSS"],
    features: [
      "You're currently viewing it",
      "Responsive layout with smooth scroll and scroll-spy",
      "Modular components and clean architecture",
    ],
    live: "https://portfolio-theta-pearl-17.vercel.app/",
  },

  {
    image: "ai-code-reviewer.png",
    title: "AI Code Reviewer",
    tech: ["AI", "Express JS", "Node JS", "React JS", "Tailwind CSS"],
    features: [
      "Interactive code editor with syntax highlighting",
      "AI-powered code review via Google Gemini",
      "Explains what the code does in plain English",
      "Finds bugs and poor practices",
      "Suggests improvements and optimized code",
      "Always outputs corrected code version",
      "Results shown in clean Markdown with highlighting",
      "Loading states with fun dynamic messages",
      "Responsive two-panel layout (editor + results)",
    ],
    live: "https://ai-code-reviewer-frontend-11rc.onrender.com/",
  },
];
